<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SurveyManagement.Infrastructure.Query.Contract\SurveyManagement.Infrastructure.Query.Contract.csproj" />
    <ProjectReference Include="..\SurveyManagement.Presentation.Facade.Contract\SurveyManagement.Presentation.Facade.Contract.csproj" />
  </ItemGroup>

</Project>
