<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Epc.Dapper" Version="1.2.7" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MeetingManagement.Application.Contracts\MeetingManagement.Application.Contracts.csproj" />
    <ProjectReference Include="..\MeetingManagement.Domain\MeetingManagement.Domain.csproj" />
    <ProjectReference Include="..\MeetingManagement.Infrastructure.Query.Contracts\MeetingManagement.Infrastructure.Query.Contracts.csproj" />
  </ItemGroup>

</Project>
